apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-0
  labels:
    pv: mongodb-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  # hostPath:
  #   path: /mnt/data/mongodb